EXP_DIR: crpn
# ICDAR 2013: 640
# ICDAR 2015: 900
# COCO-Text: 900

TRAIN:
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  SNAPSHOT_ITERS: 10000
  RPN_PRE_NMS_TOP_N: 2000
  RPN_POST_NMS_TOP_N: 2000
  USE_FLIPPED: False
  SCALE_MULTIPLE_OF: 16
  MAX_SIZE: 2000
  SCALES:
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800

TEST:
  HAS_RPN: True
  SCALE_MULTIPLE_OF: 16
  MAX_SIZE: 2000
  SCALES:
    - 900
  PT_THRESH: 0.5
  RPN_PRE_NMS_TOP_N: 1000
  RPN_POST_NMS_TOP_N: 200
  RPN_NMS_THRESH: 0.7
  BBOX_REG: True
  NMS: 0.3
